### ISSUE TITLE
occm: authentication failed lacks additional information needed to troubleshoot and causes fatal crash

### ISSUE THREAD

**Issue by samos123** [kubernetes/cloud-provider-openstack#1305]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
authentication failed with no helpful error message and unable to exec into pod because the pod crashed

see:
```
I1104 21:51:19.611606       1 serving.go:331] Generated self-signed cert in-memory
W1104 21:51:20.513695       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1104 21:51:20.516529       1 controllermanager.go:127] Version: v0.0.0-master+$Format:%h$
W1104 21:51:20.535509       1 openstack.go:305] New openstack client created failed with config: Authentication failed
F1104 21:51:20.535711       1 controllermanager.go:131] Cloud provider could not be initialized: could not init cloud provider "openstack": Authentication failed
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000138001, 0xc0005d6000, 0xa2, 0x1a5)
        /home/zuul/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2c324a0, 0xc000000003, 0x0, 0x0, 0xc0002f6310, 0x2b6569e, 0x14, 0x83, 0x0)
        /home/zuul/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x2c324a0, 0x3, 0x0, 0x0, 0x1d748ca, 0x2b, 0xc0006ada88, 0x1, 0x1)
        /home/zuul/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
        /home/zuul/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1456
k8s.io/kubernetes/cmd/cloud-controller-manager/app.Run(0xc000287d38, 0xc0001140c0, 0xc00040cf50, 0x4)
        /home/zuul/pkg/mod/k8s.io/kubernetes@v1.19.0/cmd/cloud-controller-manager/app/controllermanager.go:131 +0x1f1
main.main.func2(0xc0003402c0, 0xc000092a50, 0x0, 0x5)
        /home/zuul/src/k8s.io/cloud-provider-openstack/cmd/openstack-cloud-controller-manager/main.go:110 +0x214
github.com/spf13/cobra.(*Command).execute(0xc0003402c0, 0xc00013a130, 0x5, 0x5, 0xc0003402c0, 0xc00013a130)
        /home/zuul/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003402c0, 0x6, 0xc0002f2f70, 0x0)
        /home/zuul/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/zuul/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/zuul/src/k8s.io/cloud-provider-openstack/cmd/openstack-cloud-controller-manager/main.go:139 +0x585
```

**What you expected to happen**:
some helpful error message and ability to exec into the pod to troubleshoot

**How to reproduce it**:
have authentication fail when setting up oocm

**Anything else we need to know?**:
I am providing a private CA

see my full config here:
```
[Global]
auth-url=https://10.128.0.2:5000
username=admin
password=snip
region=RegionOne
tenant-id=demo
domain-id=default
ca-file=/etc/ssl/openstack/openstack-ca.pem
TLSInsecure=true

[LoadBalancer]
use-octavia=true
# this should be private network subnet where vip is allocated on
subnet-id=5cfb89ab-dbd2-496d-8fd7-1b799de84d70
# this is generally our public network
floating-network-id=beb35abc-7e78-42c0-b2a0-eef99c9e4324
floating-subnet-id=869fcf6b-5f04-4f98-99cd-f360c0ff865f

[BlockStorage]
bs-version=v2
```

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: `docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest`
- OpenStack version: ussuri
- Others:

**Comment by jichenjc** [comment]
I think we showed 
`Cloud provider could not be initialized: could not init cloud provider "openstack": Authentication failed`

have you tried to enable the log level from 1 to 5
then you will have info printed on what's the used stuffs to talk to openstack
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L240

I don't know what else to do

**Comment by samos123** [comment]
It turned out to be an SSL issue because the ca cert wasn't supplied correctly. Also there are no docs on how to enable the log level from 1 to 5. Could you point me to the docs that specify which configuration parameter allows you to tweak log levels? I'm using this doc to install and configure OCCM: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

**Comment by samos123** [comment]
Hmm after solving the CA issue now hitting another issue but unable to troubleshoot even after changing logging level to 5 by tweaking the arguments. See logs below:
```
I1105 19:38:19.179225       1 controllermanager.go:127] Version: v0.0.0-master+$Format:%h$                                                                                                             [115/90827]
I1105 19:38:19.179892       1 openstack.go:397] Config, loaded from the config file:
I1105 19:38:19.179942       1 openstack.go:240] AuthURL: https://10.128.0.2:5000
I1105 19:38:19.179948       1 openstack.go:241] UserID:
I1105 19:38:19.179953       1 openstack.go:242] Username: admin
I1105 19:38:19.179957       1 openstack.go:243] TenantID: demo
I1105 19:38:19.179961       1 openstack.go:244] TenantName:
I1105 19:38:19.179965       1 openstack.go:245] TrustID:
I1105 19:38:19.179969       1 openstack.go:246] DomainID: default
I1105 19:38:19.179973       1 openstack.go:247] DomainName:
I1105 19:38:19.180042       1 openstack.go:248] TenantDomainID:
I1105 19:38:19.180048       1 openstack.go:249] TenantDomainName:
I1105 19:38:19.180052       1 openstack.go:250] UserDomainID:
I1105 19:38:19.180057       1 openstack.go:251] UserDomainName:
I1105 19:38:19.180061       1 openstack.go:252] Region: RegionOne
I1105 19:38:19.180068       1 openstack.go:253] CAFile: /etc/ssl/openstack/openstack-ca.pem
I1105 19:38:19.180072       1 openstack.go:254] CertFile:
I1105 19:38:19.180199       1 openstack.go:255] KeyFile:
I1105 19:38:19.180236       1 openstack.go:256] UseClouds: false
I1105 19:38:19.180243       1 openstack.go:257] CloudsFile:
I1105 19:38:19.180247       1 openstack.go:258] Cloud:
I1105 19:38:19.180252       1 openstack.go:259] ApplicationCredentialID:
I1105 19:38:19.180257       1 openstack.go:260] ApplicationCredentialName:
I1105 19:38:19.180422       1 openstack.go:515] Using user-agent openstack-cloud-controller-manager/latest gophercloud/2.0.0
W1105 19:38:19.212407       1 openstack.go:305] New openstack client created failed with config: Authentication failed
F1105 19:38:19.212470       1 controllermanager.go:131] Cloud provider could not be initialized: could not init cloud provider "openstack": Authentication failed
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000138001, 0xc0008381c0, 0xa2, 0x1a5)
        /home/zuul/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2c324a0, 0xc000000003, 0x0, 0x0, 0xc0001b03f0, 0x2b6569e, 0x14, 0x83, 0x0)
        /home/zuul/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x2c324a0, 0x3, 0x0, 0x0, 0x1d748ca, 0x2b, 0xc000579a88, 0x1, 0x1)
        /home/zuul/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
        /home/zuul/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1456
k8s.io/kubernetes/cmd/cloud-controller-manager/app.Run(0xc000425658, 0xc0001140c0, 0xc0004fd190, 0x4)
        /home/zuul/pkg/mod/k8s.io/kubernetes@v1.19.0/cmd/cloud-controller-manager/app/controllermanager.go:131 +0x1f1
main.main.func2(0xc000164580, 0xc0001462d0, 0x0, 0x5)
        /home/zuul/src/k8s.io/cloud-provider-openstack/cmd/openstack-cloud-controller-manager/main.go:110 +0x214
github.com/spf13/cobra.(*Command).execute(0xc000164580, 0xc00013a130, 0x5, 0x5, 0xc000164580, 0xc00013a130)
        /home/zuul/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000164580, 0x6, 0xc0005f5040, 0x0)
        /home/zuul/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/zuul/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/zuul/src/k8s.io/cloud-provider-openstack/cmd/openstack-cloud-controller-manager/main.go:139 +0x585
```

Really need more verbose errors since my config seems to be correct. This is my config:
```
[Global]
auth-url=https://10.128.0.2:5000
username=admin
password=snip
region=RegionOne
tenant-id=demo
domain-id=default
ca-file=/etc/ssl/openstack/openstack-ca.pem
TLSInsecure=true

[LoadBalancer]
use-octavia=true
# this should be private network subnet where vip is allocated on
subnet-id=5cfb89ab-dbd2-496d-8fd7-1b799de84d70
# this is generally our public network
floating-network-id=beb35abc-7e78-42c0-b2a0-eef99c9e4324
floating-subnet-id=869fcf6b-5f04-4f98-99cd-f360c0ff865f

[BlockStorage]
bs-version=v2
```

am I missing something in my config?

**Comment by jichenjc** [comment]
I suggest 
1) make sure you existing stuffs workable in non-Cloud provider env (such as CLI) to make sure it is functional
2) check your deployment of OCCM, by default , it's https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml#L26 and you changed to `/etc/ssl/openstack/openstack-ca.pem` so I think that need to be changed
so please paste your occm deployment configuration and it might be helpful as well

**Comment by samos123** [comment]
this is my deployment configuration:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openstack-cloud-controller-manager
  namespace: kube-system
  labels:
    k8s-app: openstack-cloud-controller-manager
spec:
  selector:
    matchLabels:
      k8s-app: openstack-cloud-controller-manager
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: openstack-cloud-controller-manager
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        runAsUser: 1001
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: cloud-controller-manager
      containers:
        - name: openstack-cloud-controller-manager
          image: docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest
          args:
            - /bin/openstack-cloud-controller-manager
            - --v=5
            - --cloud-config=$(CLOUD_CONFIG)
            - --cloud-provider=openstack
            - --use-service-account-credentials=true
            - --bind-address=127.0.0.1
          volumeMounts:
            - mountPath: /etc/kubernetes/pki
              name: k8s-certs
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certs
              readOnly: true
            - mountPath: /etc/ssl/openstack
              name: openstack-ca-volume
              readOnly: true
            - mountPath: /etc/config
              name: cloud-config-volume
              readOnly: true
          resources:
            requests:
              cpu: 200m
          env:
            - name: CLOUD_CONFIG
              value: /etc/config/cloud.conf
      hostNetwork: true
      volumes:
      - hostPath:
          path: /etc/ssl/certs
          type: DirectoryOrCreate
        name: ca-certs
      - hostPath:
          path: /etc/kubernetes/pki
          type: DirectoryOrCreate
        name: k8s-certs
      - name: openstack-ca-volume
        secret:
          secretName: openstack-ca
      - name: cloud-config-volume
        secret:
          secretName: cloud-config
```

**Comment by jichenjc** [comment]
ca-file=/etc/ssl/openstack/openstack-ca.pem

- name: openstack-ca-volume
        secret:
          secretName: openstack-ca

not sure those 2 align with each other


here's my configuration for my CSI configuration ( i didn't use it for OCCM now)
hope this helpful
```
         volumeMounts:
           - name: cacert
             mountPath: /etc/cacert
             readOnly: true
     volumes:
       - name: cacert
         hostPath:
           path: /etc/cacert

```

**Comment by jichenjc** [comment]
ok, I found the doc talked about this cert set up, I will switch my OCCM to cert enabled env and give another try.. then paste info here

**Comment by samos123** [comment]
I think the cert part is working now since before there was a clear SSL error message which got resolved after I updated to a correct cert. Now all I'm seeing is this generic authentication error

**Comment by samos123** [comment]
Thanks to @jichenjc figured out the issue was due to tenant-id requiring the ID and doesn't allow specifying the name. It would be nice if there was a way to propagate the gopher authentication error somehow to the logs. Otherwise troubleshooting is almost impossible.

**Comment by jichenjc** [comment]
https://github.com/gophercloud/gophercloud/blob/master/provider_client.go#L424 is the code that handle the error
I think nothing special we can do for this as gophercloud wrapped the error

**Comment by samos123** [comment]
ah I see. I guess either gophercloud needs to pass the detailed error and/or log the error so somewhere it gets visible to the end-user.

**Comment by lingxiankong** [comment]
> Thanks to @jichenjc figured out the issue was due to tenant-id requiring the ID and doesn't allow specifying the name. It would be nice if there was a way to propagate the gopher authentication error somehow to the logs. Otherwise troubleshooting is almost impossible.

This is a little bit tricky because sometimes even if you provide incorrect credential to openstack CLI, all you can see is a broad error message without too much detailed information.

However, this issue could be easily avoided if you read the doc about the config options, in which it says:

```
tenant-id: Keystone project ID. 
```

Thanks for raising the issue anyway.

/close
