### ISSUE TITLE
gate: keep seeing cloud-provider-openstack-acceptance-test-lb-octavia  error

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1523]
**Is this a BUG REPORT or FEATURE REQUEST?**:

https://logs.openlabtesting.org/logs/96/1496/a6b56f6fa043e2ab52fa74d33b3b27a8014d7fc9/cloud-provider-openstack-acceptance-test-lb-octavia/cloud-provider-openstack-acceptance-test-lb-octavia/82c7945/job-output.txt.gz

```
2021-05-05 02:55:59.046250 | ubuntu-bionic |   Using cached https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz
2021-05-05 02:55:59.610182 | ubuntu-bionic |     Complete output from command python setup.py egg_info:
2021-05-05 02:55:59.610244 | ubuntu-bionic |     Traceback (most recent call last):
2021-05-05 02:55:59.610260 | ubuntu-bionic |       File "<string>", line 1, in <module>
2021-05-05 02:55:59.610283 | ubuntu-bionic |       File "/tmp/pip-build-cja04a_e/cryptography/setup.py", line 14, in <module>
2021-05-05 02:55:59.610293 | ubuntu-bionic |         from setuptools_rust import RustExtension
2021-05-05 02:55:59.610303 | ubuntu-bionic |     ModuleNotFoundError: No module named 'setuptools_rust'
2021-05-05 02:55:59.610312 | ubuntu-bionic |
2021-05-05 02:55:59.610322 | ubuntu-bionic |             =============================DEBUG ASSISTANCE==========================
2021-05-05 02:55:59.610332 | ubuntu-bionic |             If you are seeing an error here please try the following to
2021-05-05 02:55:59.610342 | ubuntu-bionic |             successfully install cryptography:
2021-05-05 02:55:59.610351 | ubuntu-bionic |
2021-05-05 02:55:59.610361 | ubuntu-bionic |             Upgrade to the latest pip and try again. This will fix errors for most
2021-05-05 02:55:59.610370 | ubuntu-bionic |             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
2021-05-05 02:55:59.610380 | ubuntu-bionic |             =============================DEBUG ASSISTANCE==========================
```
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@lingxiankong should we ask openlab help? I can a bug there if it's the right approach?

**Comment by lingxiankong** [comment]
The job has already been disabled, see https://github.com/kubernetes/cloud-provider-openstack/pull/1511
